### ISSUE TITLE
Revisit exception handling

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-fetcher#15]
The handling in question is here:
https://github.com/sul-dlss/dor-fetcher/blob/master/lib/dor-fetcher.rb#L147-L148

Firstly, it shouldn't capture and obscure every `StandardError` and then raise it as a generic `RuntimeError` with a message about "Connection Error".  For example, a `NoMethodError` should not be obscured as being about some URL.  At **most**, it should rescue `RestClient::Exception`, though even those would not be limited to being about a URL connection.

I propose that we probably should not rescue at all, or if we do, it should make a warning and then raise *exactly the same exception*.  Less obscuration, more good.  @peetucket, would appreciate any comment from you.

**Comment by peetucket** [comment]
Yes, this makes sense.  I am guessing this was put in place to get around the web service very occasionally being down.  A possible solution is to not rescue anything and let it throw exceptions, and instead use the retries gem to allow it to try a few times for those flaky situations.

**Comment by atz** [comment]
How does it help get around the web service being down?  It raises a generic exception every time anyway.

**Comment by peetucket** [comment]
It doesn't help get around the web service being down completely - you will still get an exception in that case (which is probably the correct thing to do).  But...if the web service is unvailable for only a few seconds, as it is sometimes does possibly due to network issues, this lets this app continue without an exception.  We do something like this in pre-assembly, which can often run for hours and hours at a time, which makes it more likely to hit a one or two second network glitch.  We don't want the whole calling process to terminate without retrying a couple times in that scenario.

**Comment by atz** [comment]
You misunderstand.  I get retries and have implemented them elsewhere.  You're saying of the existing (non-retrying, exception replacing) code, "this was put in place to get around the web service very occasionally being down."  I'm saying it doesn't do that.  **If** there were retries, that might help.  But raising a different exception with a misleading message doesn't.

**Comment by peetucket** [comment]
I see, sorry, yes, my comment was purely speculation - I agree the current code is not useful and is better served with retries.
